### ISSUE TITLE
Getting error when changing bot config using new admin panel

### ISSUE THREAD

**Issue by joequant** [Polygant/OpenCEX#10]
When I try to edit the bot config using the new panel I get a 403 error.  The specific log message causing an error is 

opencex  | Forbidden: /apiadmin/bots/botconfig/                                 
opencex  | 172.18.0.30 - - [22/May/2023:03:29:59 +0000] "PATCH /apiadmin/bots/botconfig/ HTTP/1.1" 403 153 "https://exchange.bitquant.com.hk/admin/page/bots_botconfig_list" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"

Any suggestions on how to debug.

**Comment by taffyatom** [comment]
Hi, we will fix it in next release

**Comment by taffyatom** [comment]
fixed
