### ISSUE TITLE
Localhost setup

### ISSUE THREAD

**Issue by ELHARAKA** [Polygant/OpenCEX#3]
How to setup on localhost

**Comment by joequant** [comment]
FYI, I haven't had much luck installing OpenCEX on a shared machine.  I think you might be able to do something with chroot.

**Comment by Stan-Polygant** [comment]
Hi, 
It is not supposed to be installed on a local machine.

**Comment by ELHARAKA** [comment]
Okay so there might be two possibilities to try.

1st is to assigne localhost to domain name "example.com" in etc/hosts 
2nd is using https://sslip.io/ (section: But I Want My Own DNS Server!) and then try again with example 127-0-0-1.sslip.io

Does that make any sense? anyway i will try and see.

**Comment by ELHARAKA** [comment]
> chroot

Ah okay i will try this too.
